### ISSUE TITLE
Bugged, can't enter stages.

### ISSUE THREAD

**Issue by KalmAndKollected** [Z4ee/Pipsi-HI3-Releases#3]
Can't enter ANY kind of stage using the latest version. It gets stuck at 83% (I tried elysian, abyss and memorial arena, none works)
(I have the game on an NVME it only takes around 2-3 secs to load)
I can enter the stage once I unload the cheat.

I had to revert back to an older version.

These are the settings that I am currently using :
SEA
Atk Multiplier : 2x
Noclip, 50 speed
Instant Win ON
Auto Skip ALL
Harassment, Peeking ON
Fov Changer set to 75
FPS, Skin Changer and Auto Challenge ON

**Comment by Z4ee** [comment]
use hotkey for instant Win

**Comment by KalmAndKollected** [comment]
> use hotkey for instant Win

I can't enter the stage so I can't use it

**Comment by Z4ee** [comment]
> > use hotkey for instant Win
> 
> I can't enter the stage so I can't use it

turn off all functions and try to enter the level

**Comment by Z4ee** [comment]
misc->config->reset

**Comment by XylioG** [comment]
Same here. 1.5 and 1.6 causing this bug
Had to revert back to 1.4
Reset config still same

**Comment by Z4ee** [comment]
what version of the game do you have?

**Comment by XylioG** [comment]
Sea v7.3.0

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-HI3-Releases/releases/tag/0.1.7

**Comment by KalmAndKollected** [comment]
I love you <3
